### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by Sxmurai** [ya-sach1/nfetch#2]
Information:
 - Arch Linux
 - i3wm
- 16GB RAM

What it outputs:
```

       _..oo8"""Y8b.._
     .88888888o.    "Yb.
   .d888P""Y8888b      "b
   o88888    88888)       "b    aesthetical     :: ixaesthetical
 d888888b..d8888P         'b    distro  :: arch linux
 88888888888888"           8    uptime  :: 14h, 54m
(88DWB8888888P             8)   wm      :: null
 8888888888P               8    shell   :: zsh
 Y88888888P     ee        .P    ram     :: 80.95% / 100%
  Y888888(     8888      oP
   "Y88888b     ""     oP"
     "Y8888o._    _.oP"
       `""Y888boodP""'
```

Description of bug(s):

- Window Manager returns null, while I am using i3wm
- My user name doesn't match up with the other entries. Might want to pad the string a bit?
- My RAM is not at 80.95%. My polybar says that I am using 23% of my RAM when running the tool. (this is overall tasks)

**Comment by ya-sach1** [comment]
I'll work on a fix soon

**Comment by ya-sach1** [comment]
Could you tell me the output of
`echo $DESKTOP_SESSION $XDG_SESSION_DESKTOP $XDG_CURRENT_DESKTOP $GDMSESSION`? ( it's supposed to give the currently running window manager or desktop enviroment )
